--- #YAML:1.0
name:                Module-LocalBuild
version:             1.012
abstract:            Detect module changes and rebuild into local area
license:             ~
author:              
    - Wilson Snyder <wsnyder@wsnyder.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Pod::Usage:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
